# Generated by Django 4.0.1 on 2022-01-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='fName',
            field=models.CharField(max_length=200, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactformdata',
            name='response',
            field=models.TextField(),
        ),
    ]
