# Generated by Django 4.0.1 on 2022-01-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0002_alter_contactformdata_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformdata',
            name='lName',
            field=models.CharField(max_length=200, verbose_name='Last Name'),
        ),
    ]
