# Generated by Django 4.0.1 on 2022-01-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactform', '0003_alter_contactformdata_lname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactformdata',
            old_name='response',
            new_name='message',
        ),
    ]
